name = "rotich-pos"
main = "src/worker.ts"
compatibility_date = "2026-09-29"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "81caff305d0f46bc85fff2b4bbf5be61"
localConnectionString = "postgresql://neondb_owner:npg_9TOJPIteB4GM@ep-restless-meadow-b5oey1j2-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"